### PR TITLE
arc and chord diagram as graphplots

### PR DESCRIPTION
**Pull request by diegozea**
Arc and chord diagrams are broken for Julia 0.5. This solves it, making arc and chord diagrams part of `graphplot`. `arcdiagram` and `chorddiagram` are not longer exported, they should be used as methods to `graphplot`:

```julia
using PlotRecipes

adjmat = Symmetric(sparse(rand(0:1,8,8)));

plot(
    graphplot(adjmat, method=:chorddiagram),
    graphplot(adjmat, method=:arcdiagram, markersize=3)
    )
```
chord_arc_diagram

### CODE REVIEW

**Comment by diegozea** [comment]
Hi @sbromberger, 
I believe that most of the `graphplot` code is yours. 
What do you think of this? 
Best regards,

**Comment by sbromberger** [comment]
@diegozea I'm not the author of the code, but if those diagrams are any indication of your change, I'm 100% in favor of it!

**Comment by diegozea** [comment]
Yes, the code and plot are after my changes :) I'm sorry, it must be @tbreloff 's code then.

**Comment by diegozea** [comment]
Travis' error is unrelated to the changes in the code.

**Comment by sbromberger** [comment]
Those are some beautiful graphs.

**Comment by sbromberger** [comment]
cc @juliohm - perhaps when this goes in we can use these visualizations in a JuliaGraphs notebook?

**Comment by mkborregaard** [comment]
Looks like noone else will review this - I looked over the code and found nothing amiss. Thanks @diegozea !

**Comment by diegozea** [comment]
Thanks @mkborregaard ! :)

**Pull request merged**
